### ISSUE TITLE
Redundant parameter [token_to_amount] in multi_route_swap function

### ISSUE THREAD

**Issue by rajeebkm** [avnu-labs/avnu-contracts#9]
- Redundant (unused) ```token_to_amount```  in ```multi_route_swap``` function. Can be removed. I have attached a screenshot for the same.

<img width="1083" alt="Screenshot 2023-09-01 at 18 09 15" src="https://github.com/avnu-labs/avnu-contracts/assets/97892873/19b9b529-72d2-4f9b-a426-a19d2637c684">

**Comment by 0xMentorNotAPseudo** [comment]
Hi

thanks for the comment and sorry for missing it. 

This repository isn't anymore maintained. I suggest you look at the latest AVNU version written in Cairo 1: https://github.com/avnu-labs/avnu-contracts-v2
